development:
  adapter: postgresql
  database: mu_development
  host: localhost

test:
  adapter: postgresql
  database: mu_test
  host: localhost

production:
  adapter: postgresql
  database: mu_production
  host: localhost
